### PR TITLE
fix:added validation for markdown editor and input title

### LINKED ISSUE #129: Blank note title is accepted
URL: https://markdown-editor.demos.testnet.verida.io/

**_Steps to replicate:_**

1. Open https://markdown-editor.demos.testnet.verida.io/
2. Create a new note
3. Update note title
4. Leave it blank
5. Click the 'Save' button
6. No error and was successfully saved. ❌
7. Select the same note
8. Click the 'Rename' option
9. Leave the Note title blank
10. Click the 'Save Changes' button
11. Error message displayed "Please fill out this field." ✔️

**_Actual Result:_** Blank note title is accepted

**_Expected Result:_** Saving a blank note title should show an error message

https://www.loom.com/share/aa399c15e1624c1386f6588b2c3edc65

### PR DESCRIPTION
**Pull request by cmcWebCode40**
- Added validation for markdown editor and input title

closes #129

### CODE REVIEW

File: src/views/Editor.jsx [hunk 1]
```diff
@@ -101,9 +102,21 @@ const Editor = ({ history, location }) => {
...
     if (pageType === 'edit') {
       data._id = selectedNote._id;
     }
+
+    if (!noteItem.title) {
+      toast.error('Please enter note title');
+      return;
+    }
+
+    if (!mdValue) {
```
Comment (aurelticot) [inline src/views/Editor.jsx:115]: I think we could allow the body to be empty, it can be helpful sometimes to prepare the note before writing it.
What do you think, @cmcWebCode40 @RochelleBondoc ?

Comment (cmcWebCode40) [reply src/views/Editor.jsx:115]: @aurelticot  
yes, you're right 
but the title field has to be required.

Comment (aurelticot) [reply src/views/Editor.jsx:115]: Yes I was only talking about the body

Comment (cmcWebCode40) [reply src/views/Editor.jsx:115]: ok

Comment (cmcWebCode40) [reply src/views/Editor.jsx]: @aurelticot, i have made the note `body` to no longer be a required field.

**Review by aurelticot — APPROVED** [review]
Ok, good to me
